<?xml version="1.0"?>
<package format="3">
    <name>ndt_pcl_modified</name>
    <version>0.1.0</version>
    <description>Modified PCL NDT backend shared library for Autoware.</description>
    <maintainer email="yamato.ando@gmail.com">Yamato Ando</maintainer>
    <license>Apache-2.0</license>

    <buildtool_depend>ament_cmake_auto</buildtool_depend>

    <depend>pcl_conversions</depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
