<?xml version="1.0"?>
<package format="3">
    <name>ndt</name>
    <version>0.1.0</version>
    <description>The ndt package</description>
    <maintainer email="yamato.ando@gmail.com">Yamato Ando</maintainer>
    <license>Apache-2.0</license>

    <buildtool_depend>ament_cmake_auto</buildtool_depend>

    <depend>ndt_pcl_modified</depend>
    <depend>ndt_omp_modified</depend>

    <export>
    </export>
</package>
