<?xml version="1.0"?>
<package format="3">
    <name>pose_initializer</name>
    <version>0.1.0</version>
    <description>Pose initialization component for Autoware localization.</description>
    <maintainer email="yamato.ando@gmail.com">Yamato Ando</maintainer>
    <license>Apache-2.0</license>

    <buildtool_depend>ament_cmake_auto</buildtool_depend>

    <depend>autoware_localization_srvs</depend>
    <depend>geometry_msgs</depend>
    <depend>pcl_conversions</depend>
    <depend>rclcpp</depend>
    <depend>rclcpp_components</depend>
    <depend>sensor_msgs</depend>
    <depend>tf2</depend>
    <depend>tf2_geometry_msgs</depend>
    <depend>tf2_ros</depend>

    <exec_depend>launch</exec_depend>
    <exec_depend>launch_ros</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
