<?xml version="1.0"?>
<package format="3">
  <name>ndt_scan_matcher</name>
  <version>0.1.0</version>
  <description>NDT-based lidar scan matcher ported to ROS 2.</description>
  <maintainer email="yamato.ando@gmail.com">Yamato Ando</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_sensor_msgs</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_eigen</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>diagnostic_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>ndt</depend>
  <depend>ndt_omp_modified</depend>
  <depend>ndt_pcl_modified</depend>
  <depend>autoware_localization_srvs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
