<?xml version="1.0"?>
<package format="3">
  <name>gnss_poser</name>
  <version>0.1.0</version>
  <description>The gnss_poser package (ported to ROS 2)</description>
  <maintainer email="watanabe-r@todo.todo">watanabe-r</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>geo_pos_conv</depend>
  <depend>geographiclib</depend>

  <exec_depend>geographiclib-tools</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
