<?xml version="1.0"?>
<package format="3">
  <name>ndt_omp_modified</name>
  <version>0.1.0</version>
  <description>OpenMP-accelerated Normal Distributions Transform backend for Autoware.</description>

  <maintainer email="yamato.ando@tier4.jp">Yamato Ando</maintainer>
  <maintainer email="koide@aisl.cs.tut.ac.jp">Koide</maintainer>

  <license>Apache-2.0</license>
  <license>BSD-2-Clause</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>pcl_conversions</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
